import { ScramjetConfig, ScramjetFlags } from "../types";
export * from "./cookie";
export * from "./headers";
export * from "./htmlRules";
export * from "./rewriters";
export * from "./security";
export declare let codecEncode: (input: string) => string;
export declare let codecDecode: (input: string) => string;
export declare function loadCodecs(): void;
export declare function flagEnabled(flag: keyof ScramjetFlags, url: URL): boolean;
export declare let config: ScramjetConfig;
export declare function setConfig(newConfig: ScramjetConfig): void;
