import { insertText } from './randomization.mjs';
export { loadTemplates as default };


const header = '<a href=/ class=brand>H­o­ly U­n­b­lo­c­k­er v5.­7.8</a> <input id=mnavecb type=checkbox> <label class=mnave for=mnavecb><span class=mnavebutton></span></label><ul class=navbar><li><a href=/?z>W­eb Pr­ox­ie­s</a><li><a href=/?g>G­a­me­s</a><li><a href=/?y>Yo­uT­u­be</a><li><a href=/?sx>Applications</a><li class=dropdown-parent><a href=#>M­or­e <i class="fas fa-ellipsis-v"></i></a><div class=dropdown-child tabindex=0><ul class=subnavbar><i class="fas fa-bars"></i><li><a href=/?x>Book­mark­lets</a><li><a href=/?in>Docs</a><li><a href=/?faq>FA­Q</a><li><a href=/?c>Credit­s</a><li><a href=/?t>TO­S</a></ul></div><li class=dropdown-parent><a href=#>Settings <i class="fas fa-tools"></i></a><div class=dropdown-child tabindex=0><div id=csel></div></div></ul>',

footer = '<div class=footerflex><div class=footerbrand><h3><a href=/ >Holy Unblocker LTS</a></h3><p>Global Web Proxy Innovation, Done Right.</div><div class=footerlist><h3>Services</h3><ul><li><a href=https://github.com/titaniumnetwork-dev/Ultraviolet target=_blank>Ultraviolet</a><li><a href=https://github.com/MercuryWorkshop/wisp-server-node target=_blank>Wisp</a><li><a href=https://discord.gg/VNT4E7gN5Y target=_blank>Rammerhead</a><li><a href=https://github.com/binary-person/womginx target=_blank>Womginx</a></ul></div><div class=footerlist><h3>About</h3><ul><li><a href=https://github.com/QuiteAFancyEmerald/Holy-Unblocker target=_blank>GitHub</a><li><a href=/?t>Privacy and Terms of Service</a><li><a href=/?c>Credits</a></ul></div><div class=footerlist><a href=#header><i class="fas fa-angle-double-up"></i></a></div></div><div class=footersocials><a href=https://github.com/QuiteAFancyEmerald/Holy-Unblocker target=_blank class=soc-github><i class="fa-github fab"></i></a> <a href=https://docs.titaniumnetwork.org target=_blank class=soc-patreon><i class="fas fa-file-code"></i></a></div><p class=copyright>Holy Unblocker LTS © 2024',

description = `<div id="info" class="box-info box-large text-center textm"> <h2>What is Holy Unblocker?</h2> <p>Holy Unblocker, an official flagship Titanium Network site, can bypass web filters or "blockers" regardless of whether it is an extension or network-based.</p><p>Being a secure web proxy service, it supports numerous sites while being updated frequently and concentrating on detail with design, mechanics, and features.</p><h2>How do I unblock websites using Holy Unblocker?</h2> <p>Head to the <a href="?z">Web Proxies</a> page and select one of the proxies featured! Afterwards, type out the site you wish to access in the search box ("example.com").</p><p>If you wish to explore the games featured on HU, check out the <a href="?g">game</a> pages.</p><h2>Don't know the difference between each web proxy?</h2> <p>Check out the use case for each proxy in the page description. A quick overview:</p><p>- Corrosion: Broad support for the majority of sites but slower (YouTube, now.gg, .io sites) <br>- Womginx: Fast but has forward support for most sites (Discord, Bing and DuckDuckGo) </p><h2>Are all sites supported? Why are some sites not loading?</h2> <p>As advanced as they are, web proxies are not perfect. This means that some sites may not be supported by any of the proxies listed here due to limitations or security measures.</p><p>This also applies to speed; naturally things will be slower or broken under a proxy versus direct access.</p></div>`,

loadTemplates = str => {
    str = insertText("<!--HEADER-->", str, header);
    str = insertText("<!--FOOTER-->", str, footer);
    str = insertText("<!--DESC-->", str, description);
    return str;
};